name: Odds ETL

on:
  schedule:
    # Run every 15 minutes during NFL season (Thu-Mon)
    - cron: '*/15 * * * 4-1'
  workflow_dispatch: # Allow manual trigger

jobs:
  fetch-odds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r packages/models/requirements.txt

      - name: Run odds ETL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
        run: |
          python ops/scripts/odds_etl.py --live --sport nfl --api the-odds-api

      - name: Notify on failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST $SLACK_WEBHOOK_URL \
            -H 'Content-Type: application/json' \
            -d '{"text":"⚠️ Odds ETL failed - check GitHub Actions logs"}'
