name: Settle Results

on:
  schedule:
    # Run nightly at 2 AM ET (6 AM UTC)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  settle-bets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r packages/models/requirements.txt

      - name: Settle bet results
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python ops/scripts/settle_results.py --auto

      - name: Notify on failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST $SLACK_WEBHOOK_URL \
            -H 'Content-Type: application/json' \
            -d '{"text":"⚠️ Results settlement failed - check GitHub Actions logs"}'
